#!/bin/zsh

for folder in $(echo */ | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow --dotfiles -D $folder
done

# Uninstall neovim
if [ -d "/opt/nvim-linux-x86_64/" ];  then
    echo "Removing neovim installation"
    sudo rm -rf /opt/nvim-linux-x86_64
    sudo rm /usr/local/bin/nvim
fi

# Remove the saved plugins directory if present
if [ -d "./tmux/dot-config/tmux/plugins" ];  then
    echo "Removing TMUX plugins directory"
    rm -rf ./tmux/dot-config/tmux/plugins
fi

# Remove the oh-my-zsh installation

if [ -d "$HOME/.oh-my-zsh/" ];  then
    echo "Removing oh-my-zsh installation"
    rm -rf $HOME/.oh-my-zsh/
fi
