#!/bin/zsh

for folder in $(echo */ | sed "s/,/ /g")
do
    echo "Stowing $folder"
    stow --dotfiles -D $folder
    stow --dotfiles $folder
done

# Install neovim
nvim --version
if [ $? -ne 0 ];  then
    echo "Neovim is not installed, installing latest version..."
    wget https://github.com/neovim/neovim-releases/releases/latest/download/nvim-linux-x86_64.tar.gz
    sudo tar xzvf nvim-linux-x86_64.tar.gz -C /opt/
    sudo ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim
    rm nvim-linux-x86_64.tar.gz
fi

# Install tpm
if [ ! -d "$HOME/.config/tmux/plugins/tpm" ];  then
    echo "TMUX plugin directory does not exist"
    git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
fi

# Install oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ];  then
    echo "oh-my-zsh directory does not exist"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended
fi

echo "\nMake sure you <prefix>I in TMUX to install the plugins!"
zsh
