#!/bin/zsh

for folder in $(echo */ | sed "s/,/ /g")
do
    echo "Stowing $folder"
    stow --dotfiles -D $folder
    stow --dotfiles $folder
done

# Install tpm
if [ ! -d "$HOME/.config/tmux/plugins/tpm" ];  then
    echo "TMUX plugin directory does not exist"
    git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
fi

# Install oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ];  then
    echo "oh-my-zsh directory does not exist"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended
fi

echo "\nMake sure you <prefix>I in TMUX to install the plugins!"
zsh
